LIB_SRC = Channel.cc EventLoop.cc EventLoopThread.cc Poller.cc  TimerQueue.cc   Accept.cc TcpConnection.cc   InetAddress.cc   Buffer.cc      ThreadPool.cc   Logger.c   SerializationAntiserialization.hpp   BaseRPC.hpp   TcpClient.cc                                                                    
BINARIES =  test7

all: $(BINARIES)

include ../reactor.mk

test1: test1.cc
test2: test2.cc
test3: test3.cc
test4: test4.cc
test5: test5.cc
test6: test6.cc
test7: test7.cc


